import 'progression_models.dart';

const _questAssetActivity = 'assets/ui/quests/activity.png';
const _questAssetDoubleWin = 'assets/ui/quests/double_win.png';
const _questAssetNutrition = 'assets/ui/quests/nutri_combo.png';
const _questAssetSteps = 'assets/ui/quests/steps.png';
const _questAssetStreak = 'assets/ui/quests/streak.png';

class ProgressionQuestCatalog {
  const ProgressionQuestCatalog();

  List<ProgressionQuestDefinition> build() {
    return [
      ProgressionQuestDefinition(
        id: 'earn_first_reward',
        title: (l10n) => l10n.progQuestEarnFirstRewardTitle,
        description: (l10n) => l10n.progQuestEarnFirstRewardDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 1,
        rewardXp: 80,
        sortOrder: 10,
        priority: 100,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'reward_hunter',
        chainStepLabel: (l10n) => '1',
        nextQuestIds: ['earn_25_rewards'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_two_goals_today',
        title: (l10n) => l10n.progQuestDailyTwoGoalsTodayTitle,
        description: (l10n) => l10n.progQuestDailyTwoGoalsTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 2,
        rewardXp: 140,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_calories',
          'daily_protein',
          'daily_sleep',
        ],
        sortOrder: 12,
        priority: 100,
        assetKey: _questAssetDoubleWin,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyCombo,
        chainId: 'daily_combo',
        chainStepLabel: (l10n) => '2',
        nextQuestIds: ['daily_triple_win_today'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'daily_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'daily_combo',
        dailySequenceStep: 1,
      ),
      ProgressionQuestDefinition(
        id: 'daily_triple_win_today',
        title: (l10n) => l10n.progQuestDailyTripleWinTodayTitle,
        description: (l10n) => l10n.progQuestDailyTripleWinTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 3,
        rewardXp: 190,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_calories',
          'daily_protein',
          'daily_sleep',
        ],
        sortOrder: 13,
        priority: 97,
        assetKey: _questAssetDoubleWin,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyCombo,
        chainId: 'daily_combo',
        chainStepLabel: (l10n) => '3',
        nextQuestIds: ['daily_four_pillars_today'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'daily_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'daily_combo',
        dailySequenceStep: 2,
      ),
      ProgressionQuestDefinition(
        id: 'daily_four_pillars_today',
        title: (l10n) => l10n.progQuestDailyFourPillarsTodayTitle,
        description: (l10n) => l10n.progQuestDailyFourPillarsTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 4,
        rewardXp: 230,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_calories',
          'daily_protein',
          'daily_sleep',
        ],
        minimumLevel: 8,
        minimumTrackedDays: 14,
        sortOrder: 14,
        priority: 99,
        assetKey: _questAssetDoubleWin,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyCombo,
        chainId: 'daily_combo',
        chainStepLabel: (l10n) => '4',
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'daily_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'daily_combo',
        dailySequenceStep: 3,
      ),
      ProgressionQuestDefinition(
        id: 'daily_nutrition_combo_today',
        title: (l10n) => l10n.progQuestDailyNutritionComboTodayTitle,
        description: (l10n) => l10n.progQuestDailyNutritionComboTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 2,
        rewardXp: 100,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_calories',
          'daily_protein',
        ],
        sortOrder: 16,
        priority: 95,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_combo',
        chainStepLabel: (l10n) => '2',
        nextQuestIds: ['daily_nutrition_carbs_combo_today'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'nutrition_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'nutrition_combo',
        dailySequenceStep: 1,
      ),
      ProgressionQuestDefinition(
        id: 'daily_nutrition_carbs_combo_today',
        title: (l10n) => l10n.progQuestDailyNutritionCarbsComboTodayTitle,
        description: (l10n) => l10n.progQuestDailyNutritionCarbsComboTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 3,
        rewardXp: 130,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_calories',
          'daily_protein',
          'daily_carbs',
        ],
        sortOrder: 17,
        priority: 94,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_combo',
        chainStepLabel: (l10n) => '3',
        nextQuestIds: ['daily_nutrition_fat_combo_today'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'nutrition_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'nutrition_combo',
        dailySequenceStep: 2,
      ),
      ProgressionQuestDefinition(
        id: 'daily_nutrition_fat_combo_today',
        title: (l10n) => l10n.progQuestDailyNutritionFatComboTodayTitle,
        description: (l10n) => l10n.progQuestDailyNutritionFatComboTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 4,
        rewardXp: 160,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_calories',
          'daily_protein',
          'daily_carbs',
          'daily_fat',
        ],
        sortOrder: 18,
        priority: 93,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_combo',
        chainStepLabel: (l10n) => '4',
        nextQuestIds: ['daily_nutrition_fiber_combo_today'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'nutrition_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'nutrition_combo',
        dailySequenceStep: 3,
      ),
      ProgressionQuestDefinition(
        id: 'daily_nutrition_fiber_combo_today',
        title: (l10n) => l10n.progQuestDailyNutritionFiberComboTodayTitle,
        description: (l10n) => l10n.progQuestDailyNutritionFiberComboTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 5,
        rewardXp: 200,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_calories',
          'daily_protein',
          'daily_carbs',
          'daily_fat',
          'daily_fiber',
        ],
        minimumTrackedDays: 5,
        sortOrder: 19,
        priority: 92,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_combo',
        chainStepLabel: (l10n) => '5',
        nextQuestIds: ['nutrition_rhythm_3'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'nutrition_combo',
        comboPoolId: 'daily_combo_pool',
        dailySequenceId: 'nutrition_combo',
        dailySequenceStep: 4,
      ),
      ProgressionQuestDefinition(
        id: 'nutrition_rhythm_3',
        title: (l10n) => l10n.progQuestNutritionRhythm3Title,
        description: (l10n) => l10n.progQuestNutritionRhythm3Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.achievementUnlocked,
        targetValue: 1,
        rewardXp: 160,
        achievementId: 'nutrition_streak_3',
        minimumTrackedDays: 5,
        sortOrder: 20,
        priority: 76,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_combo',
        chainStepLabel: (l10n) => '3',
        displayBucket: ProgressionQuestDisplayBucket.longTerm,
        displayGroupId: 'nutrition_combo',
      ),
      ProgressionQuestDefinition(
        id: 'daily_recovery_focus_today',
        title: (l10n) => l10n.progQuestDailyRecoveryFocusTodayTitle,
        description: (l10n) => l10n.progQuestDailyRecoveryFocusTodayDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 2,
        rewardXp: 130,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_sleep',
        ],
        minimumLevel: 6,
        minimumTrackedDays: 5,
        sortOrder: 24,
        priority: 93,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.sleep,
        sourceLabel: (l10n) => l10n.progQuestSourceRecovery,
        chainId: 'recovery_combo',
        chainStepLabel: (l10n) => '2',
        nextQuestIds: ['sleep_total_250h'],
        displayBucket: ProgressionQuestDisplayBucket.daily,
        displayGroupId: 'recovery_combo',
        comboPoolId: 'daily_combo_pool',
      ),
      ProgressionQuestDefinition(
        id: 'sleep_total_250h',
        title: (l10n) => l10n.progQuestSleepTotal250hTitle,
        description: (l10n) => l10n.progQuestSleepTotal250hDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 15000,
        rewardXp: 240,
        ruleId: 'daily_sleep',
        periodKind: ProgressionPeriodKind.day,
        minimumTrackedDays: 21,
        prerequisiteQuestIds: ['daily_recovery_focus_today'],
        sortOrder: 25,
        priority: 58,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.sleep,
        sourceLabel: (l10n) => l10n.progQuestSourceRecovery,
        chainId: 'recovery_combo',
        chainStepLabel: (l10n) => '250h',
        displayBucket: ProgressionQuestDisplayBucket.longTerm,
        displayGroupId: 'recovery_combo',
      ),
      ProgressionQuestDefinition(
        id: 'daily_steps_today',
        title: (l10n) => l10n.progQuestDailyStepsTodayTitle,
        description: (l10n) => l10n.progQuestDailyStepsTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 80,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 17,
        priority: 88,
        assetKey: _questAssetSteps,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepSteps,
        nextQuestIds: ['daily_calories_today'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_calories_today',
        title: (l10n) => l10n.progQuestDailyCaloriesTodayTitle,
        description: (l10n) => l10n.progQuestDailyCaloriesTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 60,
        ruleId: 'daily_calories',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 18,
        priority: 86,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepKcal,
        nextQuestIds: ['daily_protein_today'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_protein_today',
        title: (l10n) => l10n.progQuestDailyProteinTodayTitle,
        description: (l10n) => l10n.progQuestDailyProteinTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 40,
        ruleId: 'daily_protein',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 19,
        priority: 84,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepProtein,
        nextQuestIds: ['daily_carbs_today'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_carbs_today',
        title: (l10n) => l10n.progQuestDailyCarbsTodayTitle,
        description: (l10n) => l10n.progQuestDailyCarbsTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 35,
        ruleId: 'daily_carbs',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 20,
        priority: 83,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepCarbs,
        nextQuestIds: ['daily_fat_today'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_fat_today',
        title: (l10n) => l10n.progQuestDailyFatTodayTitle,
        description: (l10n) => l10n.progQuestDailyFatTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 35,
        ruleId: 'daily_fat',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 21,
        priority: 82,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepFat,
        nextQuestIds: ['daily_fiber_today'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_fiber_today',
        title: (l10n) => l10n.progQuestDailyFiberTodayTitle,
        description: (l10n) => l10n.progQuestDailyFiberTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 45,
        ruleId: 'daily_fiber',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 22,
        priority: 81,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepFiber,
        nextQuestIds: ['daily_sleep_today'],
      ),
      ProgressionQuestDefinition(
        id: 'daily_sleep_today',
        title: (l10n) => l10n.progQuestDailySleepTodayTitle,
        description: (l10n) => l10n.progQuestDailySleepTodayDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        rewardXp: 50,
        ruleId: 'daily_sleep',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 23,
        priority: 82,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.sleep,
        sourceLabel: (l10n) => l10n.progQuestSourceDailyGoal,
        chainId: 'daily_goals',
        chainStepLabel: (l10n) => l10n.progQuestChainStepSleep,
      ),
      ProgressionQuestDefinition(
        id: 'reach_500_xp',
        title: (l10n) => l10n.progQuestReach500XpTitle,
        description: (l10n) => l10n.progQuestReach500XpDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 500,
        rewardXp: 120,
        sortOrder: 30,
        priority: 90,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'xp_milestones',
        chainStepLabel: (l10n) => '500',
        nextQuestIds: ['reach_2000_xp'],
      ),
      ProgressionQuestDefinition(
        id: 'reach_2000_xp',
        title: (l10n) => l10n.progQuestReach2000XpTitle,
        description: (l10n) => l10n.progQuestReach2000XpDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 2000,
        rewardXp: 180,
        prerequisiteQuestIds: ['reach_500_xp'],
        sortOrder: 40,
        priority: 80,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'xp_milestones',
        chainStepLabel: (l10n) => '2K',
        nextQuestIds: ['reach_5000_xp'],
      ),
      ProgressionQuestDefinition(
        id: 'reach_5000_xp',
        title: (l10n) => l10n.progQuestReach5000XpTitle,
        description: (l10n) => l10n.progQuestReach5000XpDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 5000,
        rewardXp: 260,
        minimumLevel: 8,
        minimumTrackedDays: 10,
        prerequisiteQuestIds: ['reach_2000_xp'],
        sortOrder: 50,
        priority: 72,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'xp_milestones',
        chainStepLabel: (l10n) => '5K',
        nextQuestIds: ['reach_25000_xp'],
      ),
      ProgressionQuestDefinition(
        id: 'reach_25000_xp',
        title: (l10n) => l10n.progQuestReach25000XpTitle,
        description: (l10n) => l10n.progQuestReach25000XpDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 25000,
        rewardXp: 420,
        minimumLevel: 15,
        minimumTrackedDays: 21,
        prerequisiteQuestIds: ['reach_5000_xp'],
        sortOrder: 52,
        priority: 58,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'xp_milestones',
        chainStepLabel: (l10n) => '25K',
        nextQuestIds: ['reach_100000_xp'],
      ),
      ProgressionQuestDefinition(
        id: 'reach_100000_xp',
        title: (l10n) => l10n.progQuestReach100000XpTitle,
        description: (l10n) => l10n.progQuestReach100000XpDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 100000,
        rewardXp: 640,
        minimumLevel: 30,
        minimumTrackedDays: 45,
        prerequisiteQuestIds: ['reach_25000_xp'],
        sortOrder: 54,
        priority: 48,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'xp_milestones',
        chainStepLabel: (l10n) => '100K',
        nextQuestIds: ['reach_1000000_xp'],
      ),
      ProgressionQuestDefinition(
        id: 'reach_1000000_xp',
        title: (l10n) => l10n.progQuestReach1000000XpTitle,
        description: (l10n) => l10n.progQuestReach1000000XpDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 1000000,
        rewardXp: 1000,
        minimumLevel: 80,
        minimumTrackedDays: 120,
        prerequisiteQuestIds: ['reach_100000_xp'],
        sortOrder: 56,
        priority: 38,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'xp_milestones',
        chainStepLabel: (l10n) => '1M',
      ),
      ProgressionQuestDefinition(
        id: 'earn_25_rewards',
        title: (l10n) => l10n.progQuestEarn25RewardsTitle,
        description: (l10n) => l10n.progQuestEarn25RewardsDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 25,
        rewardXp: 180,
        prerequisiteQuestIds: ['earn_first_reward'],
        sortOrder: 60,
        priority: 75,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'reward_hunter',
        chainStepLabel: (l10n) => '25',
        nextQuestIds: ['earn_100_rewards'],
      ),
      ProgressionQuestDefinition(
        id: 'earn_100_rewards',
        title: (l10n) => l10n.progQuestEarn100RewardsTitle,
        description: (l10n) => l10n.progQuestEarn100RewardsDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 100,
        rewardXp: 320,
        minimumLevel: 10,
        minimumTrackedDays: 21,
        prerequisiteQuestIds: ['earn_25_rewards'],
        sortOrder: 70,
        priority: 66,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'reward_hunter',
        chainStepLabel: (l10n) => '100',
        nextQuestIds: ['earn_250_rewards'],
      ),
      ProgressionQuestDefinition(
        id: 'earn_250_rewards',
        title: (l10n) => l10n.progQuestEarn250RewardsTitle,
        description: (l10n) => l10n.progQuestEarn250RewardsDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 250,
        rewardXp: 520,
        minimumLevel: 20,
        minimumTrackedDays: 45,
        prerequisiteQuestIds: ['earn_100_rewards'],
        sortOrder: 72,
        priority: 54,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceJourney,
        chainId: 'reward_hunter',
        chainStepLabel: (l10n) => '250',
      ),
      ProgressionQuestDefinition(
        id: 'nutrition_rewards_5',
        title: (l10n) => l10n.progQuestNutritionRewards5Title,
        description: (l10n) => l10n.progQuestNutritionRewards5Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.domainRewardCountAtLeast,
        targetValue: 5,
        rewardXp: 140,
        domain: ProgressionDomain.nutrition,
        sortOrder: 80,
        priority: 78,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_rewards',
        chainStepLabel: (l10n) => '5',
        nextQuestIds: ['nutrition_rewards_25'],
      ),
      ProgressionQuestDefinition(
        id: 'nutrition_rewards_25',
        title: (l10n) => l10n.progQuestNutritionRewards25Title,
        description: (l10n) => l10n.progQuestNutritionRewards25Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.domainRewardCountAtLeast,
        targetValue: 25,
        rewardXp: 260,
        domain: ProgressionDomain.nutrition,
        minimumLevel: 7,
        minimumTrackedDays: 10,
        prerequisiteQuestIds: ['nutrition_rewards_5'],
        sortOrder: 90,
        priority: 64,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_rewards',
        chainStepLabel: (l10n) => '25',
        nextQuestIds: ['nutrition_rewards_100'],
      ),
      ProgressionQuestDefinition(
        id: 'nutrition_rewards_100',
        title: (l10n) => l10n.progQuestNutritionRewards100Title,
        description: (l10n) => l10n.progQuestNutritionRewards100Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.domainRewardCountAtLeast,
        targetValue: 100,
        rewardXp: 460,
        domain: ProgressionDomain.nutrition,
        minimumLevel: 16,
        minimumTrackedDays: 35,
        prerequisiteQuestIds: ['nutrition_rewards_25'],
        sortOrder: 92,
        priority: 50,
        assetKey: _questAssetNutrition,
        visualDomain: ProgressionDomain.nutrition,
        sourceLabel: (l10n) => l10n.progQuestSourceNutrition,
        chainId: 'nutrition_rewards',
        chainStepLabel: (l10n) => '100',
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_100k',
        title: (l10n) => l10n.progQuestTotalSteps100kTitle,
        description: (l10n) => l10n.progQuestTotalSteps100kDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 100000,
        rewardXp: 160,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumTrackedDays: 7,
        sortOrder: 100,
        priority: 70,
        assetKey: _questAssetSteps,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceSteps,
        chainId: 'total_steps',
        chainStepLabel: (l10n) => '100K',
        nextQuestIds: ['total_steps_500k'],
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_500k',
        title: (l10n) => l10n.progQuestTotalSteps500kTitle,
        description: (l10n) => l10n.progQuestTotalSteps500kDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 500000,
        rewardXp: 260,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        prerequisiteQuestIds: ['total_steps_100k'],
        sortOrder: 110,
        priority: 62,
        assetKey: _questAssetSteps,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceSteps,
        chainId: 'total_steps',
        chainStepLabel: (l10n) => '500K',
        nextQuestIds: ['total_steps_1m'],
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_1m',
        title: (l10n) => l10n.progQuestTotalSteps1mTitle,
        description: (l10n) => l10n.progQuestTotalSteps1mDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 1000000,
        rewardXp: 420,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        prerequisiteQuestIds: ['total_steps_500k'],
        sortOrder: 112,
        priority: 54,
        assetKey: _questAssetSteps,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceSteps,
        chainId: 'total_steps',
        chainStepLabel: (l10n) => '1M',
        nextQuestIds: ['total_steps_5m'],
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_5m',
        title: (l10n) => l10n.progQuestTotalSteps5mTitle,
        description: (l10n) => l10n.progQuestTotalSteps5mDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 5000000,
        rewardXp: 760,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 30,
        minimumTrackedDays: 90,
        prerequisiteQuestIds: ['total_steps_1m'],
        sortOrder: 114,
        priority: 42,
        assetKey: _questAssetSteps,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceSteps,
        chainId: 'total_steps',
        chainStepLabel: (l10n) => '5M',
        nextQuestIds: ['total_steps_10m'],
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_10m',
        title: (l10n) => l10n.progQuestTotalSteps10mTitle,
        description: (l10n) => l10n.progQuestTotalSteps10mDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 10000000,
        rewardXp: 1100,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 60,
        minimumTrackedDays: 180,
        prerequisiteQuestIds: ['total_steps_5m'],
        sortOrder: 116,
        priority: 34,
        assetKey: _questAssetSteps,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceSteps,
        chainId: 'total_steps',
        chainStepLabel: (l10n) => '10M',
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_3',
        title: (l10n) => l10n.progQuestStepsStreak3Title,
        description: (l10n) => l10n.progQuestStepsStreak3Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 3,
        rewardXp: 120,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 120,
        priority: 96,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => '3',
        nextQuestIds: ['unlock_step_chain'],
      ),
      ProgressionQuestDefinition(
        id: 'unlock_step_chain',
        title: (l10n) => l10n.progQuestUnlockStepChainTitle,
        description: (l10n) => l10n.progQuestUnlockStepChainDesc,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.achievementUnlocked,
        targetValue: 1,
        rewardXp: 160,
        achievementId: 'steps_streak_3',
        prerequisiteQuestIds: ['steps_streak_3'],
        sortOrder: 130,
        priority: 78,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => l10n.progQuestChainStepBadge,
        nextQuestIds: ['steps_streak_7'],
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_7',
        title: (l10n) => l10n.progQuestStepsStreak7Title,
        description: (l10n) => l10n.progQuestStepsStreak7Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 7,
        rewardXp: 180,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        prerequisiteQuestIds: ['unlock_step_chain'],
        sortOrder: 140,
        priority: 72,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => '7',
        nextQuestIds: ['steps_streak_14'],
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_14',
        title: (l10n) => l10n.progQuestStepsStreak14Title,
        description: (l10n) => l10n.progQuestStepsStreak14Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 14,
        rewardXp: 260,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 10,
        minimumTrackedDays: 21,
        prerequisiteQuestIds: ['steps_streak_7'],
        sortOrder: 150,
        priority: 64,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => '14',
        nextQuestIds: ['steps_streak_30'],
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_30',
        title: (l10n) => l10n.progQuestStepsStreak30Title,
        description: (l10n) => l10n.progQuestStepsStreak30Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 30,
        rewardXp: 420,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 18,
        minimumTrackedDays: 35,
        prerequisiteQuestIds: ['steps_streak_14'],
        sortOrder: 152,
        priority: 54,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => '30',
        nextQuestIds: ['steps_streak_50'],
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_50',
        title: (l10n) => l10n.progQuestStepsStreak50Title,
        description: (l10n) => l10n.progQuestStepsStreak50Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 50,
        rewardXp: 620,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 28,
        minimumTrackedDays: 60,
        prerequisiteQuestIds: ['steps_streak_30'],
        sortOrder: 154,
        priority: 44,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => '50',
        nextQuestIds: ['steps_streak_100'],
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_100',
        title: (l10n) => l10n.progQuestStepsStreak100Title,
        description: (l10n) => l10n.progQuestStepsStreak100Desc,
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 100,
        rewardXp: 1000,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 60,
        minimumTrackedDays: 120,
        prerequisiteQuestIds: ['steps_streak_50'],
        sortOrder: 156,
        priority: 34,
        assetKey: _questAssetStreak,
        visualDomain: ProgressionDomain.steps,
        sourceLabel: (l10n) => l10n.progQuestSourceStepChain,
        chainId: 'steps_streak',
        chainStepLabel: (l10n) => '100',
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_once',
        title: (l10n) => l10n.progQuestWeeklyActivityOnceTitle,
        description: (l10n) => l10n.progQuestWeeklyActivityOnceDesc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 1,
        rewardXp: 120,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        sortOrder: 160,
        priority: 88,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceWeekly,
        chainId: 'weekly_activity',
        chainStepLabel: (l10n) => '1',
        nextQuestIds: ['weekly_activity_4'],
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_4',
        title: (l10n) => l10n.progQuestWeeklyActivity4Title,
        description: (l10n) => l10n.progQuestWeeklyActivity4Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 4,
        rewardXp: 180,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        prerequisiteQuestIds: ['weekly_activity_once'],
        sortOrder: 170,
        priority: 72,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceWeekly,
        chainId: 'weekly_activity',
        chainStepLabel: (l10n) => '4',
        nextQuestIds: ['weekly_activity_12'],
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_12',
        title: (l10n) => l10n.progQuestWeeklyActivity12Title,
        description: (l10n) => l10n.progQuestWeeklyActivity12Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 12,
        rewardXp: 280,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        minimumLevel: 8,
        minimumTrackedDays: 42,
        prerequisiteQuestIds: ['weekly_activity_4'],
        sortOrder: 180,
        priority: 60,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceWeekly,
        chainId: 'weekly_activity',
        chainStepLabel: (l10n) => '12',
        nextQuestIds: ['weekly_activity_24'],
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_24',
        title: (l10n) => l10n.progQuestWeeklyActivity24Title,
        description: (l10n) => l10n.progQuestWeeklyActivity24Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 24,
        rewardXp: 460,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        minimumLevel: 18,
        minimumTrackedDays: 84,
        prerequisiteQuestIds: ['weekly_activity_12'],
        sortOrder: 182,
        priority: 46,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceWeekly,
        chainId: 'weekly_activity',
        chainStepLabel: (l10n) => '24',
        nextQuestIds: ['weekly_activity_52'],
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_52',
        title: (l10n) => l10n.progQuestWeeklyActivity52Title,
        description: (l10n) => l10n.progQuestWeeklyActivity52Desc,
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 52,
        rewardXp: 900,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        minimumLevel: 40,
        minimumTrackedDays: 240,
        prerequisiteQuestIds: ['weekly_activity_24'],
        sortOrder: 184,
        priority: 32,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: (l10n) => l10n.progQuestSourceWeekly,
        chainId: 'weekly_activity',
        chainStepLabel: (l10n) => '52',
      ),
      ..._journeyChapterDefinitions(),
    ];
  }
}

List<ProgressionQuestDefinition> _journeyChapterDefinitions() {
  final specs = <_JourneyChapterSpec>[
    _JourneyChapterSpec(
      id: 'forest_trial',
      level: 10,
      sortOrder: 300,
      sourceLabel: (l10n) => l10n.progQuestSourceForestTrial,
      openTitle: (l10n) => l10n.progQuestForestTrialOpenTitle,
      openDescription: (l10n) => l10n.progQuestForestTrialOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestForestTrialFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestForestTrialFinaleDesc,
      rewards: const [120, 180, 180, 220, 300],
      steps: [
        _JourneyChapterStepSpec(
          id: 'forest_trial_daily_wins_5',
          title: (l10n) => l10n.progQuestForestTrialDailyWins5Title,
          description: (l10n) => l10n.progQuestForestTrialDailyWins5Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 5,
          requiredRuleCount: 2,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const [
            'daily_steps',
            'daily_calories',
            'daily_protein',
            'daily_sleep',
          ],
          assetKey: _questAssetDoubleWin,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '5',
        ),
        _JourneyChapterStepSpec(
          id: 'forest_trial_steps_5',
          title: (l10n) => l10n.progQuestForestTrialSteps5Title,
          description: (l10n) => l10n.progQuestForestTrialSteps5Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 5,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '5',
        ),
        _JourneyChapterStepSpec(
          id: 'forest_trial_recovery_3',
          title: (l10n) => l10n.progQuestForestTrialRecovery3Title,
          description: (l10n) => l10n.progQuestForestTrialRecovery3Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 3,
          requiredRuleCount: 2,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const ['daily_steps', 'daily_sleep'],
          assetKey: _questAssetStreak,
          visualDomain: ProgressionDomain.sleep,
          chainStepLabel: (l10n) => '3',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'ruins_discipline',
      level: 20,
      sortOrder: 320,
      sourceLabel: (l10n) => l10n.progQuestSourceRuinsDiscipline,
      openTitle: (l10n) => l10n.progQuestRuinsDisciplineOpenTitle,
      openDescription: (l10n) => l10n.progQuestRuinsDisciplineOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestRuinsDisciplineFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestRuinsDisciplineFinaleDesc,
      rewards: const [180, 260, 280, 320, 450],
      steps: [
        _JourneyChapterStepSpec(
          id: 'ruins_discipline_nutrition_7',
          title: (l10n) => l10n.progQuestRuinsDisciplineNutrition7Title,
          description: (l10n) => l10n.progQuestRuinsDisciplineNutrition7Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 7,
          requiredRuleCount: 2,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const ['daily_calories', 'daily_protein'],
          assetKey: _questAssetNutrition,
          visualDomain: ProgressionDomain.nutrition,
          chainStepLabel: (l10n) => '7',
        ),
        _JourneyChapterStepSpec(
          id: 'ruins_discipline_weekly_2',
          title: (l10n) => l10n.progQuestRuinsDisciplineWeekly2Title,
          description: (l10n) => l10n.progQuestRuinsDisciplineWeekly2Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 2,
          ruleId: 'weekly_activity',
          periodKind: ProgressionPeriodKind.week,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '2',
        ),
        _JourneyChapterStepSpec(
          id: 'ruins_discipline_steps_10',
          title: (l10n) => l10n.progQuestRuinsDisciplineSteps10Title,
          description: (l10n) => l10n.progQuestRuinsDisciplineSteps10Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 10,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '10',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'mine_descent',
      level: 30,
      sortOrder: 340,
      sourceLabel: (l10n) => l10n.progQuestSourceMineDescent,
      openTitle: (l10n) => l10n.progQuestMineDescentOpenTitle,
      openDescription: (l10n) => l10n.progQuestMineDescentOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestMineDescentFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestMineDescentFinaleDesc,
      rewards: const [240, 380, 420, 420, 600],
      steps: [
        _JourneyChapterStepSpec(
          id: 'mine_descent_steps_250k',
          title: (l10n) => l10n.progQuestMineDescentSteps250kTitle,
          description: (l10n) => l10n.progQuestMineDescentSteps250kDesc,
          criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
          targetValue: 250000,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '250K',
        ),
        _JourneyChapterStepSpec(
          id: 'mine_descent_activity_rewards_12',
          title: (l10n) => l10n.progQuestMineDescentActivityRewards12Title,
          description: (l10n) => l10n.progQuestMineDescentActivityRewards12Desc,
          criterionType: ProgressionQuestCriterionType.domainRewardCountAtLeast,
          targetValue: 12,
          domain: ProgressionDomain.activity,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '12',
        ),
        _JourneyChapterStepSpec(
          id: 'mine_descent_protein_10',
          title: (l10n) => l10n.progQuestMineDescentProtein10Title,
          description: (l10n) => l10n.progQuestMineDescentProtein10Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 10,
          ruleId: 'daily_protein',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetNutrition,
          visualDomain: ProgressionDomain.nutrition,
          chainStepLabel: (l10n) => '10',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'forge_momentum',
      level: 40,
      sortOrder: 360,
      sourceLabel: (l10n) => l10n.progQuestSourceForgeMomentum,
      openTitle: (l10n) => l10n.progQuestForgeMomentumOpenTitle,
      openDescription: (l10n) => l10n.progQuestForgeMomentumOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestForgeMomentumFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestForgeMomentumFinaleDesc,
      rewards: const [300, 480, 520, 560, 750],
      steps: [
        _JourneyChapterStepSpec(
          id: 'forge_momentum_weekly_4',
          title: (l10n) => l10n.progQuestForgeMomentumWeekly4Title,
          description: (l10n) => l10n.progQuestForgeMomentumWeekly4Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 4,
          ruleId: 'weekly_activity',
          periodKind: ProgressionPeriodKind.week,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '4',
        ),
        _JourneyChapterStepSpec(
          id: 'forge_momentum_steps_20',
          title: (l10n) => l10n.progQuestForgeMomentumSteps20Title,
          description: (l10n) => l10n.progQuestForgeMomentumSteps20Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 20,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '20',
        ),
        _JourneyChapterStepSpec(
          id: 'forge_momentum_nutrition_15',
          title: (l10n) => l10n.progQuestForgeMomentumNutrition15Title,
          description: (l10n) => l10n.progQuestForgeMomentumNutrition15Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 15,
          requiredRuleCount: 2,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const ['daily_calories', 'daily_protein'],
          assetKey: _questAssetNutrition,
          visualDomain: ProgressionDomain.nutrition,
          chainStepLabel: (l10n) => '15',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'underway_pact',
      level: 50,
      sortOrder: 380,
      sourceLabel: (l10n) => l10n.progQuestSourceUnderwayPact,
      openTitle: (l10n) => l10n.progQuestUnderwayPactOpenTitle,
      openDescription: (l10n) => l10n.progQuestUnderwayPactOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestUnderwayPactFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestUnderwayPactFinaleDesc,
      rewards: const [360, 600, 620, 680, 900],
      steps: [
        _JourneyChapterStepSpec(
          id: 'underway_pact_four_pillars_5',
          title: (l10n) => l10n.progQuestUnderwayPactFourPillars5Title,
          description: (l10n) => l10n.progQuestUnderwayPactFourPillars5Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 5,
          requiredRuleCount: 4,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const [
            'daily_steps',
            'daily_calories',
            'daily_protein',
            'daily_sleep',
          ],
          assetKey: _questAssetDoubleWin,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '5',
        ),
        _JourneyChapterStepSpec(
          id: 'underway_pact_sleep_14',
          title: (l10n) => l10n.progQuestUnderwayPactSleep14Title,
          description: (l10n) => l10n.progQuestUnderwayPactSleep14Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 14,
          ruleId: 'daily_sleep',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetStreak,
          visualDomain: ProgressionDomain.sleep,
          chainStepLabel: (l10n) => '14',
        ),
        _JourneyChapterStepSpec(
          id: 'underway_pact_recovery_10',
          title: (l10n) => l10n.progQuestUnderwayPactRecovery10Title,
          description: (l10n) => l10n.progQuestUnderwayPactRecovery10Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 10,
          requiredRuleCount: 2,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const ['daily_steps', 'daily_sleep'],
          assetKey: _questAssetStreak,
          visualDomain: ProgressionDomain.sleep,
          chainStepLabel: (l10n) => '10',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'frostbound_oath',
      level: 60,
      sortOrder: 400,
      sourceLabel: (l10n) => l10n.progQuestSourceFrostboundOath,
      openTitle: (l10n) => l10n.progQuestFrostboundOathOpenTitle,
      openDescription: (l10n) => l10n.progQuestFrostboundOathOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestFrostboundOathFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestFrostboundOathFinaleDesc,
      rewards: const [420, 720, 760, 800, 1100],
      steps: [
        _JourneyChapterStepSpec(
          id: 'frostbound_oath_steps_21',
          title: (l10n) => l10n.progQuestFrostboundOathSteps21Title,
          description: (l10n) => l10n.progQuestFrostboundOathSteps21Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 21,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '21',
        ),
        _JourneyChapterStepSpec(
          id: 'frostbound_oath_sleep_21',
          title: (l10n) => l10n.progQuestFrostboundOathSleep21Title,
          description: (l10n) => l10n.progQuestFrostboundOathSleep21Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 21,
          ruleId: 'daily_sleep',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetStreak,
          visualDomain: ProgressionDomain.sleep,
          chainStepLabel: (l10n) => '21',
        ),
        _JourneyChapterStepSpec(
          id: 'frostbound_oath_weekly_6',
          title: (l10n) => l10n.progQuestFrostboundOathWeekly6Title,
          description: (l10n) => l10n.progQuestFrostboundOathWeekly6Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 6,
          ruleId: 'weekly_activity',
          periodKind: ProgressionPeriodKind.week,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '6',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'icewalker_route',
      level: 70,
      sortOrder: 420,
      sourceLabel: (l10n) => l10n.progQuestSourceIcewalkerRoute,
      openTitle: (l10n) => l10n.progQuestIcewalkerRouteOpenTitle,
      openDescription: (l10n) => l10n.progQuestIcewalkerRouteOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestIcewalkerRouteFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestIcewalkerRouteFinaleDesc,
      rewards: const [500, 850, 900, 950, 1300],
      steps: [
        _JourneyChapterStepSpec(
          id: 'icewalker_route_steps_500k',
          title: (l10n) => l10n.progQuestIcewalkerRouteSteps500kTitle,
          description: (l10n) => l10n.progQuestIcewalkerRouteSteps500kDesc,
          criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
          targetValue: 500000,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '500K',
        ),
        _JourneyChapterStepSpec(
          id: 'icewalker_route_rewards_150',
          title: (l10n) => l10n.progQuestIcewalkerRouteRewards150Title,
          description: (l10n) => l10n.progQuestIcewalkerRouteRewards150Desc,
          criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
          targetValue: 150,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '150',
        ),
        _JourneyChapterStepSpec(
          id: 'icewalker_route_protein_30',
          title: (l10n) => l10n.progQuestIcewalkerRouteProtein30Title,
          description: (l10n) => l10n.progQuestIcewalkerRouteProtein30Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 30,
          ruleId: 'daily_protein',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetNutrition,
          visualDomain: ProgressionDomain.nutrition,
          chainStepLabel: (l10n) => '30',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'mountain_ascent',
      level: 80,
      sortOrder: 440,
      sourceLabel: (l10n) => l10n.progQuestSourceMountainAscent,
      openTitle: (l10n) => l10n.progQuestMountainAscentOpenTitle,
      openDescription: (l10n) => l10n.progQuestMountainAscentOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestMountainAscentFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestMountainAscentFinaleDesc,
      rewards: const [600, 1000, 1100, 1150, 1600],
      steps: [
        _JourneyChapterStepSpec(
          id: 'mountain_ascent_four_pillars_15',
          title: (l10n) => l10n.progQuestMountainAscentFourPillars15Title,
          description: (l10n) => l10n.progQuestMountainAscentFourPillars15Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 15,
          requiredRuleCount: 4,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const [
            'daily_steps',
            'daily_calories',
            'daily_protein',
            'daily_sleep',
          ],
          assetKey: _questAssetDoubleWin,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '15',
        ),
        _JourneyChapterStepSpec(
          id: 'mountain_ascent_steps_30',
          title: (l10n) => l10n.progQuestMountainAscentSteps30Title,
          description: (l10n) => l10n.progQuestMountainAscentSteps30Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 30,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '30',
        ),
        _JourneyChapterStepSpec(
          id: 'mountain_ascent_weekly_10',
          title: (l10n) => l10n.progQuestMountainAscentWeekly10Title,
          description: (l10n) => l10n.progQuestMountainAscentWeekly10Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 10,
          ruleId: 'weekly_activity',
          periodKind: ProgressionPeriodKind.week,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '10',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'dragonroad',
      level: 90,
      sortOrder: 460,
      sourceLabel: (l10n) => l10n.progQuestSourceDragonroad,
      openTitle: (l10n) => l10n.progQuestDragonroadOpenTitle,
      openDescription: (l10n) => l10n.progQuestDragonroadOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestDragonroadFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestDragonroadFinaleDesc,
      rewards: const [750, 1250, 1350, 1400, 2000],
      steps: [
        _JourneyChapterStepSpec(
          id: 'dragonroad_rewards_250',
          title: (l10n) => l10n.progQuestDragonroadRewards250Title,
          description: (l10n) => l10n.progQuestDragonroadRewards250Desc,
          criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
          targetValue: 250,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '250',
        ),
        _JourneyChapterStepSpec(
          id: 'dragonroad_four_pillars_25',
          title: (l10n) => l10n.progQuestDragonroadFourPillars25Title,
          description: (l10n) => l10n.progQuestDragonroadFourPillars25Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 25,
          requiredRuleCount: 4,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const [
            'daily_steps',
            'daily_calories',
            'daily_protein',
            'daily_sleep',
          ],
          assetKey: _questAssetDoubleWin,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '25',
        ),
        _JourneyChapterStepSpec(
          id: 'dragonroad_weekly_12',
          title: (l10n) => l10n.progQuestDragonroadWeekly12Title,
          description: (l10n) => l10n.progQuestDragonroadWeekly12Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 12,
          ruleId: 'weekly_activity',
          periodKind: ProgressionPeriodKind.week,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '12',
        ),
      ],
    ),
    _JourneyChapterSpec(
      id: 'dragonrock_sovereign',
      level: 100,
      sortOrder: 480,
      sourceLabel: (l10n) => l10n.progQuestSourceDragonrockSovereign,
      openTitle: (l10n) => l10n.progQuestDragonrockSovereignOpenTitle,
      openDescription: (l10n) => l10n.progQuestDragonrockSovereignOpenDesc,
      finaleTitle: (l10n) => l10n.progQuestDragonrockSovereignFinaleTitle,
      finaleDescription: (l10n) => l10n.progQuestDragonrockSovereignFinaleDesc,
      rewards: const [900, 1500, 1600, 1800, 2600],
      steps: [
        _JourneyChapterStepSpec(
          id: 'dragonrock_sovereign_four_pillars_30',
          title: (l10n) => l10n.progQuestDragonrockSovereignFourPillars30Title,
          description: (l10n) =>
              l10n.progQuestDragonrockSovereignFourPillars30Desc,
          criterionType:
              ProgressionQuestCriterionType.ruleSetCompletionsAtLeast,
          targetValue: 30,
          requiredRuleCount: 4,
          periodKind: ProgressionPeriodKind.day,
          relatedRuleIds: const [
            'daily_steps',
            'daily_calories',
            'daily_protein',
            'daily_sleep',
          ],
          assetKey: _questAssetDoubleWin,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '30',
        ),
        _JourneyChapterStepSpec(
          id: 'dragonrock_sovereign_weekly_16',
          title: (l10n) => l10n.progQuestDragonrockSovereignWeekly16Title,
          description: (l10n) => l10n.progQuestDragonrockSovereignWeekly16Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 16,
          ruleId: 'weekly_activity',
          periodKind: ProgressionPeriodKind.week,
          assetKey: _questAssetActivity,
          visualDomain: ProgressionDomain.activity,
          chainStepLabel: (l10n) => '16',
        ),
        _JourneyChapterStepSpec(
          id: 'dragonrock_sovereign_steps_50',
          title: (l10n) => l10n.progQuestDragonrockSovereignSteps50Title,
          description: (l10n) => l10n.progQuestDragonrockSovereignSteps50Desc,
          criterionType: ProgressionQuestCriterionType.ruleCompletionsAtLeast,
          targetValue: 50,
          ruleId: 'daily_steps',
          periodKind: ProgressionPeriodKind.day,
          assetKey: _questAssetSteps,
          visualDomain: ProgressionDomain.steps,
          chainStepLabel: (l10n) => '50',
        ),
      ],
    ),
  ];

  return [
    for (final spec in specs) ...spec.build(),
  ];
}

class _JourneyChapterSpec {
  const _JourneyChapterSpec({
    required this.id,
    required this.level,
    required this.sortOrder,
    required this.sourceLabel,
    required this.openTitle,
    required this.openDescription,
    required this.finaleTitle,
    required this.finaleDescription,
    required this.rewards,
    required this.steps,
  });

  final String id;
  final int level;
  final int sortOrder;
  final ProgressionQuestText sourceLabel;
  final ProgressionQuestText openTitle;
  final ProgressionQuestText openDescription;
  final ProgressionQuestText finaleTitle;
  final ProgressionQuestText finaleDescription;
  final List<int> rewards;
  final List<_JourneyChapterStepSpec> steps;

  List<ProgressionQuestDefinition> build() {
    final openId = '${id}_open';
    final finaleId = '${id}_finale';
    final stepIds = [for (final step in steps) step.id];

    return [
      ProgressionQuestDefinition(
        id: openId,
        title: openTitle,
        description: openDescription,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.chapter,
        criterionType: ProgressionQuestCriterionType.chapterStarted,
        targetValue: 1,
        rewardXp: rewards[0],
        minimumLevel: level,
        sortOrder: sortOrder,
        priority: 86,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: sourceLabel,
        chainId: id,
        chainStepLabel: (l10n) => l10n.progQuestChainStepStart,
        nextQuestIds: [steps.first.id],
        displayBucket: ProgressionQuestDisplayBucket.chapter,
        displayGroupId: id,
        chapterId: id,
        progressStartPolicy: ProgressionProgressStartPolicy.chapterStartedAt,
      ),
      for (var index = 0; index < steps.length; index++)
        steps[index].build(
          chapterId: id,
          sourceLabel: sourceLabel,
          rewardXp: rewards[index + 1],
          sortOrder: sortOrder + index + 1,
          prerequisiteQuestId: index == 0 ? openId : steps[index - 1].id,
          nextQuestId:
              index == steps.length - 1 ? finaleId : steps[index + 1].id,
        ),
      ProgressionQuestDefinition(
        id: finaleId,
        title: finaleTitle,
        description: finaleDescription,
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.chapter,
        criterionType: ProgressionQuestCriterionType.chapterStarted,
        targetValue: 1,
        rewardXp: rewards.last,
        prerequisiteQuestIds: stepIds,
        sortOrder: sortOrder + 4,
        priority: 82,
        assetKey: _questAssetActivity,
        visualDomain: ProgressionDomain.activity,
        sourceLabel: sourceLabel,
        chainId: id,
        chainStepLabel: (l10n) => l10n.progQuestChainStepEmblem,
        displayBucket: ProgressionQuestDisplayBucket.chapter,
        displayGroupId: id,
        chapterId: id,
        progressStartPolicy: ProgressionProgressStartPolicy.chapterStartedAt,
      ),
    ];
  }
}

class _JourneyChapterStepSpec {
  const _JourneyChapterStepSpec({
    required this.id,
    required this.title,
    required this.description,
    required this.criterionType,
    required this.targetValue,
    required this.assetKey,
    required this.visualDomain,
    required this.chainStepLabel,
    this.ruleId,
    this.domain,
    this.periodKind,
    this.relatedRuleIds = const [],
    this.requiredRuleCount,
  });

  final String id;
  final ProgressionQuestText title;
  final ProgressionQuestText description;
  final ProgressionQuestCriterionType criterionType;
  final int targetValue;
  final String assetKey;
  final ProgressionDomain visualDomain;
  final ProgressionQuestText chainStepLabel;
  final String? ruleId;
  final ProgressionDomain? domain;
  final ProgressionPeriodKind? periodKind;
  final List<String> relatedRuleIds;
  final int? requiredRuleCount;

  ProgressionQuestDefinition build({
    required String chapterId,
    required ProgressionQuestText sourceLabel,
    required int rewardXp,
    required int sortOrder,
    required String prerequisiteQuestId,
    required String nextQuestId,
  }) {
    return ProgressionQuestDefinition(
      id: id,
      title: title,
      description: description,
      type: ProgressionQuestType.mastery,
      category: ProgressionQuestCategory.chapter,
      criterionType: criterionType,
      targetValue: targetValue,
      rewardXp: rewardXp,
      ruleId: ruleId,
      domain: domain,
      periodKind: periodKind,
      relatedRuleIds: relatedRuleIds,
      requiredRuleCount: requiredRuleCount,
      prerequisiteQuestIds: [prerequisiteQuestId],
      sortOrder: sortOrder,
      priority: 84,
      assetKey: assetKey,
      visualDomain: visualDomain,
      sourceLabel: sourceLabel,
      chainId: chapterId,
      chainStepLabel: chainStepLabel,
      nextQuestIds: [nextQuestId],
      displayBucket: ProgressionQuestDisplayBucket.chapter,
      displayGroupId: chapterId,
      chapterId: chapterId,
      progressStartPolicy: ProgressionProgressStartPolicy.chapterStartedAt,
    );
  }
}
