import 'progression_models.dart';

class ProgressionQuestCatalog {
  const ProgressionQuestCatalog();

  List<ProgressionQuestDefinition> build() {
    return const [
      ProgressionQuestDefinition(
        id: 'earn_first_reward',
        title: 'Earn First Reward',
        description: 'Earn your first progression reward.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 1,
        sortOrder: 10,
        priority: 100,
      ),
      ProgressionQuestDefinition(
        id: 'daily_two_goals_today',
        title: 'Double Win',
        description: 'Complete any 2 daily goals in the current day.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 2,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_calories',
          'daily_protein',
          'daily_sleep',
        ],
        sortOrder: 12,
        priority: 100,
      ),
      ProgressionQuestDefinition(
        id: 'daily_triple_win_today',
        title: 'Triple Win',
        description: 'Complete any 3 daily goals in the current day.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 3,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_calories',
          'daily_protein',
          'daily_sleep',
        ],
        prerequisiteQuestIds: ['daily_two_goals_today'],
        sortOrder: 13,
        priority: 97,
      ),
      ProgressionQuestDefinition(
        id: 'daily_four_pillars_today',
        title: 'Four Pillars',
        description: 'Complete all 4 daily goals in the current day.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 4,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_calories',
          'daily_protein',
          'daily_sleep',
        ],
        minimumLevel: 8,
        minimumTrackedDays: 14,
        prerequisiteQuestIds: ['daily_triple_win_today'],
        sortOrder: 14,
        priority: 99,
      ),
      ProgressionQuestDefinition(
        id: 'daily_nutrition_combo_today',
        title: 'Nutrition Combo',
        description:
            'Complete both calorie and protein goals in the current day.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 2,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_calories',
          'daily_protein',
        ],
        sortOrder: 15,
        priority: 95,
      ),
      ProgressionQuestDefinition(
        id: 'daily_recovery_focus_today',
        title: 'Recovery Focus',
        description: 'Complete both steps and sleep goals in the current day.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleSetAtLeast,
        targetValue: 2,
        periodKind: ProgressionPeriodKind.day,
        relatedRuleIds: [
          'daily_steps',
          'daily_sleep',
        ],
        minimumLevel: 6,
        minimumTrackedDays: 5,
        sortOrder: 16,
        priority: 93,
      ),
      ProgressionQuestDefinition(
        id: 'daily_steps_today',
        title: "Today's Step Goal",
        description: 'Complete the daily steps rule in the current day.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 17,
        priority: 88,
      ),
      ProgressionQuestDefinition(
        id: 'daily_calories_today',
        title: "Today's Calorie Goal",
        description: 'Complete the daily calorie rule in the current day.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        ruleId: 'daily_calories',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 18,
        priority: 86,
      ),
      ProgressionQuestDefinition(
        id: 'daily_protein_today',
        title: "Today's Protein Goal",
        description: 'Complete the daily protein rule in the current day.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        ruleId: 'daily_protein',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 19,
        priority: 84,
      ),
      ProgressionQuestDefinition(
        id: 'daily_sleep_today',
        title: "Today's Sleep Goal",
        description: 'Complete the daily sleep rule in the current day.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.daily,
        criterionType:
            ProgressionQuestCriterionType.currentPeriodRuleCompletion,
        targetValue: 1,
        ruleId: 'daily_sleep',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 20,
        priority: 82,
      ),
      ProgressionQuestDefinition(
        id: 'reach_500_xp',
        title: 'Reach 500 XP',
        description: 'Accumulate at least 500 XP.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 500,
        sortOrder: 30,
        priority: 90,
      ),
      ProgressionQuestDefinition(
        id: 'reach_2000_xp',
        title: 'Reach 2,000 XP',
        description: 'Accumulate at least 2,000 XP.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 2000,
        prerequisiteQuestIds: ['reach_500_xp'],
        sortOrder: 40,
        priority: 80,
      ),
      ProgressionQuestDefinition(
        id: 'reach_5000_xp',
        title: 'Reach 5,000 XP',
        description: 'Accumulate at least 5,000 XP.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalXpAtLeast,
        targetValue: 5000,
        minimumLevel: 8,
        minimumTrackedDays: 10,
        prerequisiteQuestIds: ['reach_2000_xp'],
        sortOrder: 50,
        priority: 72,
      ),
      ProgressionQuestDefinition(
        id: 'earn_25_rewards',
        title: 'Earn 25 Rewards',
        description: 'Collect 25 progression rewards in total.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 25,
        prerequisiteQuestIds: ['earn_first_reward'],
        sortOrder: 60,
        priority: 75,
      ),
      ProgressionQuestDefinition(
        id: 'earn_100_rewards',
        title: 'Earn 100 Rewards',
        description: 'Collect 100 progression rewards in total.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 100,
        minimumLevel: 10,
        minimumTrackedDays: 21,
        prerequisiteQuestIds: ['earn_25_rewards'],
        sortOrder: 70,
        priority: 66,
      ),
      ProgressionQuestDefinition(
        id: 'nutrition_rewards_5',
        title: 'Nutrition Rhythm',
        description: 'Earn 5 nutrition rewards.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.domainRewardCountAtLeast,
        targetValue: 5,
        domain: ProgressionDomain.nutrition,
        sortOrder: 80,
        priority: 78,
      ),
      ProgressionQuestDefinition(
        id: 'nutrition_rewards_25',
        title: 'Nutrition Mastery',
        description: 'Earn 25 nutrition rewards.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.domainRewardCountAtLeast,
        targetValue: 25,
        domain: ProgressionDomain.nutrition,
        minimumLevel: 7,
        minimumTrackedDays: 10,
        prerequisiteQuestIds: ['nutrition_rewards_5'],
        sortOrder: 90,
        priority: 64,
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_100k',
        title: 'Walk 100K Steps',
        description: 'Accumulate 100,000 total steps.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 100000,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumTrackedDays: 7,
        sortOrder: 100,
        priority: 70,
      ),
      ProgressionQuestDefinition(
        id: 'total_steps_500k',
        title: 'Walk 500K Steps',
        description: 'Accumulate 500,000 total steps.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.journey,
        criterionType: ProgressionQuestCriterionType.totalRuleValueAtLeast,
        targetValue: 500000,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        prerequisiteQuestIds: ['total_steps_100k'],
        sortOrder: 110,
        priority: 62,
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_3',
        title: 'Steps Streak',
        description: 'Complete the daily steps rule 3 periods in a row.',
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 3,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        sortOrder: 120,
        priority: 96,
      ),
      ProgressionQuestDefinition(
        id: 'unlock_step_chain',
        title: 'Unlock Step Chain',
        description: 'Unlock the Step Chain achievement.',
        type: ProgressionQuestType.milestone,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.achievementUnlocked,
        targetValue: 1,
        achievementId: 'steps_streak_3',
        prerequisiteQuestIds: ['steps_streak_3'],
        sortOrder: 130,
        priority: 78,
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_7',
        title: 'Step Discipline',
        description: 'Complete the daily steps rule 7 periods in a row.',
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 7,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        prerequisiteQuestIds: ['unlock_step_chain'],
        sortOrder: 140,
        priority: 72,
      ),
      ProgressionQuestDefinition(
        id: 'steps_streak_14',
        title: 'Step Guardian',
        description: 'Complete the daily steps rule 14 periods in a row.',
        type: ProgressionQuestType.streak,
        category: ProgressionQuestCategory.chain,
        criterionType: ProgressionQuestCriterionType.bestStreakAtLeast,
        targetValue: 14,
        ruleId: 'daily_steps',
        periodKind: ProgressionPeriodKind.day,
        minimumLevel: 10,
        minimumTrackedDays: 21,
        prerequisiteQuestIds: ['steps_streak_7'],
        sortOrder: 150,
        priority: 64,
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_once',
        title: 'Weekly Activity',
        description: 'Complete the weekly activity rule once.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 1,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        sortOrder: 160,
        priority: 88,
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_4',
        title: 'Weekly Activity Momentum',
        description: 'Complete the weekly activity rule 4 times.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 4,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        prerequisiteQuestIds: ['weekly_activity_once'],
        sortOrder: 170,
        priority: 72,
      ),
      ProgressionQuestDefinition(
        id: 'weekly_activity_12',
        title: 'Weekly Activity Legend',
        description: 'Complete the weekly activity rule 12 times.',
        type: ProgressionQuestType.mastery,
        category: ProgressionQuestCategory.weekly,
        criterionType: ProgressionQuestCriterionType.rewardCountAtLeast,
        targetValue: 12,
        ruleId: 'weekly_activity',
        periodKind: ProgressionPeriodKind.week,
        minimumLevel: 8,
        minimumTrackedDays: 42,
        prerequisiteQuestIds: ['weekly_activity_4'],
        sortOrder: 180,
        priority: 60,
      ),
    ];
  }
}
