import 'progression_level_config.dart';
import 'progression_level_policy.dart';
import 'progression_models.dart';

class ProgressionAchievementCatalog {
  const ProgressionAchievementCatalog();

  List<ProgressionAchievementDefinition> build() {
    const levelPolicy = ProgressionLevelPolicy();
    return [
      // Visible welcome reward — fires immediately on first sync because
      // every player satisfies `totalXp >= 0`. Drives the
      // `welcome_to_journey` → background_camp + emblem_pilgrim_mark mapping
      // in CosmeticRewardTable so the player sees a real achievement
      // rather than a silent default unlock.
      ProgressionAchievementDefinition(
        id: 'welcome_to_journey',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Welcome to the Journey',
        description: 'You set out on the road.',
        targetValue: 0,
      ),
      ProgressionAchievementDefinition(
        id: 'first_reward',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'First Reward',
        description: 'Earn your first progression reward.',
        targetValue: 1,
      ),
      // Level milestone achievements — generated from kProgressionLevelTiers.
      // Level 1 is the journey origin (not a milestone the player "earns") so
      // it is excluded from the catalog. Title and description are fallbacks
      // only — the live UI reads them through ProgressionL10n which routes to
      // the localized progLevelTitle*/progLevelAchievementDesc keys.
      for (final tier in kProgressionLevelTiers.where((t) => t.level > 1))
        ProgressionAchievementDefinition(
          id: tier.achievementId,
          type: ProgressionAchievementType.milestone,
          difficulty: tier.difficulty,
          criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
          title: 'Level ${tier.level}',
          description: 'Reach level ${tier.level} through earned XP.',
          targetValue: levelPolicy.xpRequiredForLevel(tier.level),
        ),
      ProgressionAchievementDefinition(
        id: 'steps_total_100k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Centurion Walker',
        description: 'Accumulate 100,000 total steps.',
        targetValue: 100000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_3',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Step Chain',
        description: 'Hit the daily steps rule for 3 periods in a row.',
        targetValue: 3,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_streak_3',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Balanced Rhythm',
        description:
            'Earn at least one nutrition reward for 3 periods in a row.',
        targetValue: 3,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_mastery',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Weekly Warrior',
        description: 'Complete the weekly activity rule at least once.',
        targetValue: 1,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_total_250h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Rested Soul',
        description: 'Accumulate 250 hours of tracked sleep.',
        targetValue: 15000,
        ruleId: 'daily_sleep',
      ),
      ProgressionAchievementDefinition(
        id: 'reward_hunter_25',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Reward Hunter',
        description: 'Earn 25 progression rewards.',
        targetValue: 25,
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_500k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Half-Million March',
        description: 'Accumulate 500,000 total steps.',
        targetValue: 500000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_7',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Step Discipline',
        description: 'Hit the daily steps rule for 7 periods in a row.',
        targetValue: 7,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_rewards_25',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Macro Maestro',
        description: 'Earn 25 nutrition rewards.',
        targetValue: 25,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_4',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Activity Vanguard',
        description: 'Complete the weekly activity rule 4 times.',
        targetValue: 4,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_month_300k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Trail Builder',
        description: 'Accumulate 300,000 steps across any 30-day window.',
        targetValue: 300000,
        ruleId: 'daily_steps',
        windowSizeDays: 30,
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_total_1000h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Dream Archivist',
        description: 'Accumulate 1,000 hours of tracked sleep.',
        targetValue: 60000,
        ruleId: 'daily_sleep',
      ),
      ProgressionAchievementDefinition(
        id: 'reward_hunter_100',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Reward Legend',
        description: 'Earn 100 progression rewards.',
        targetValue: 100,
      ),
      ProgressionAchievementDefinition(
        id: 'xp_100000',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Ascendant',
        description: 'Accumulate 100,000 XP.',
        targetValue: 100000,
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_1000000',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Million Step Myth',
        description: 'Accumulate 1,000,000 total steps.',
        targetValue: 1000000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_30',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Step Sovereign',
        description: 'Hit the daily steps rule for 30 periods in a row.',
        targetValue: 30,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_50',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Iron Resolve',
        description: 'Hit the daily steps rule for 50 periods in a row.',
        targetValue: 50,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_streak_30',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Macro Momentum',
        description:
            'Earn at least one nutrition reward for 30 periods in a row.',
        targetValue: 30,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_12',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Seasoned Mover',
        description: 'Complete the weekly activity rule 12 times.',
        targetValue: 12,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_24',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Unbroken Momentum',
        description: 'Complete the weekly activity rule 24 times.',
        targetValue: 24,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_month_600k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Iron Pilgrim',
        description: 'Accumulate 600,000 steps across any 30-day window.',
        targetValue: 600000,
        ruleId: 'daily_steps',
        windowSizeDays: 30,
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_month_225h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Deep Reset',
        description: 'Accumulate 225 hours of sleep across any 30-day window.',
        targetValue: 13500,
        ruleId: 'daily_sleep',
        windowSizeDays: 30,
      ),
      ProgressionAchievementDefinition(
        id: 'xp_1000000',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Radiant Ascension',
        description: 'Accumulate 1,000,000 XP.',
        targetValue: 1000000,
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_5000000',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Gemstone Path',
        description: 'Accumulate 5,000,000 total steps.',
        targetValue: 5000000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_10000000',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Summit of Legends',
        description: 'Accumulate 10,000,000 total steps.',
        targetValue: 10000000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_100',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Iron Chain',
        description: 'Hit the daily steps rule for 100 periods in a row.',
        targetValue: 100,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_streak_100',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Kitchen Discipline',
        description:
            'Earn at least one nutrition reward for 100 periods in a row.',
        targetValue: 100,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_52',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Yearlong Engine',
        description: 'Complete the weekly activity rule 52 times.',
        targetValue: 52,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_month_240h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Perfect Recovery',
        description: 'Accumulate 240 hours of sleep across any 30-day window.',
        targetValue: 14400,
        ruleId: 'daily_sleep',
        windowSizeDays: 30,
      ),
    ];
  }
}
