import 'progression_level_policy.dart';
import 'progression_models.dart';

class ProgressionAchievementCatalog {
  const ProgressionAchievementCatalog();

  List<ProgressionAchievementDefinition> build() {
    const levelPolicy = ProgressionLevelPolicy();
    return [
      ProgressionAchievementDefinition(
        id: 'first_reward',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'First Reward',
        description: 'Earn your first progression reward.',
        targetValue: 1,
      ),
      ProgressionAchievementDefinition(
        id: 'pathfinder_level_5',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Pathfinder',
        description: 'Reach level 5 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(5),
      ),
      ProgressionAchievementDefinition(
        id: 'trail_vanguard_level_10',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Trail Vanguard',
        description: 'Reach level 10 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(10),
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_100k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Centurion Walker',
        description: 'Accumulate 100,000 total steps.',
        targetValue: 100000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_3',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Step Chain',
        description: 'Hit the daily steps rule for 3 periods in a row.',
        targetValue: 3,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_streak_3',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Balanced Rhythm',
        description:
            'Earn at least one nutrition reward for 3 periods in a row.',
        targetValue: 3,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_mastery',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Weekly Warrior',
        description: 'Complete the weekly activity rule at least once.',
        targetValue: 1,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_total_250h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.easy,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Rested Soul',
        description: 'Accumulate 250 hours of tracked sleep.',
        targetValue: 15000,
        ruleId: 'daily_sleep',
      ),
      ProgressionAchievementDefinition(
        id: 'reward_hunter_25',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Reward Hunter',
        description: 'Earn 25 progression rewards.',
        targetValue: 25,
      ),
      ProgressionAchievementDefinition(
        id: 'forge_knight_level_15',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Forge Knight',
        description: 'Reach level 15 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(15),
      ),
      ProgressionAchievementDefinition(
        id: 'iron_warden_level_20',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Iron Warden',
        description: 'Reach level 20 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(20),
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_500k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Half-Million March',
        description: 'Accumulate 500,000 total steps.',
        targetValue: 500000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_7',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Step Discipline',
        description: 'Hit the daily steps rule for 7 periods in a row.',
        targetValue: 7,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_rewards_25',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Macro Maestro',
        description: 'Earn 25 nutrition rewards.',
        targetValue: 25,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_4',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Activity Vanguard',
        description: 'Complete the weekly activity rule 4 times.',
        targetValue: 4,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_month_300k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Trail Builder',
        description: 'Accumulate 300,000 steps across any 30-day window.',
        targetValue: 300000,
        ruleId: 'daily_steps',
        windowSizeDays: 30,
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_total_1000h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.medium,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Dream Archivist',
        description: 'Accumulate 1,000 hours of tracked sleep.',
        targetValue: 60000,
        ruleId: 'daily_sleep',
      ),
      ProgressionAchievementDefinition(
        id: 'reward_hunter_100',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Reward Legend',
        description: 'Earn 100 progression rewards.',
        targetValue: 100,
      ),
      ProgressionAchievementDefinition(
        id: 'storm_herald_level_25',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Storm Herald',
        description: 'Reach level 25 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(25),
      ),
      ProgressionAchievementDefinition(
        id: 'dawn_sentinel_level_30',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Dawn Sentinel',
        description: 'Reach level 30 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(30),
      ),
      ProgressionAchievementDefinition(
        id: 'rift_walker_level_40',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Rift Walker',
        description: 'Reach level 40 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(40),
      ),
      ProgressionAchievementDefinition(
        id: 'xp_100000',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Ascendant',
        description: 'Accumulate 100,000 XP.',
        targetValue: 100000,
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_1000000',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Million Step Myth',
        description: 'Accumulate 1,000,000 total steps.',
        targetValue: 1000000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_30',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Step Sovereign',
        description: 'Hit the daily steps rule for 30 periods in a row.',
        targetValue: 30,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_streak_30',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Macro Momentum',
        description:
            'Earn at least one nutrition reward for 30 periods in a row.',
        targetValue: 30,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_12',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Seasoned Mover',
        description: 'Complete the weekly activity rule 12 times.',
        targetValue: 12,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_24',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Unbroken Momentum',
        description: 'Complete the weekly activity rule 24 times.',
        targetValue: 24,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_month_600k',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Iron Pilgrim',
        description: 'Accumulate 600,000 steps across any 30-day window.',
        targetValue: 600000,
        ruleId: 'daily_steps',
        windowSizeDays: 30,
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_month_225h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.hard,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Deep Reset',
        description: 'Accumulate 225 hours of sleep across any 30-day window.',
        targetValue: 13500,
        ruleId: 'daily_sleep',
        windowSizeDays: 30,
      ),
      ProgressionAchievementDefinition(
        id: 'xp_1000000',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Mythic Rank',
        description: 'Accumulate 1,000,000 XP.',
        targetValue: 1000000,
      ),
      ProgressionAchievementDefinition(
        id: 'mythic_ranger_level_50',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Mythic Ranger',
        description: 'Reach level 50 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(50),
      ),
      ProgressionAchievementDefinition(
        id: 'titan_forger_level_60',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Titan Forger',
        description: 'Reach level 60 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(60),
      ),
      ProgressionAchievementDefinition(
        id: 'astral_champion_level_70',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Astral Champion',
        description: 'Reach level 70 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(70),
      ),
      ProgressionAchievementDefinition(
        id: 'eternal_paragon_level_80',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Eternal Paragon',
        description: 'Reach level 80 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(80),
      ),
      ProgressionAchievementDefinition(
        id: 'realm_sovereign_level_90',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Realm Sovereign',
        description: 'Reach level 90 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(90),
      ),
      ProgressionAchievementDefinition(
        id: 'living_legend_level_100',
        type: ProgressionAchievementType.milestone,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.totalXpAtLeast,
        title: 'Living Legend',
        description: 'Reach level 100 through earned XP.',
        targetValue: levelPolicy.xpRequiredForLevel(100),
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_5000000',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Endless Road',
        description: 'Accumulate 5,000,000 total steps.',
        targetValue: 5000000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_total_10000000',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType:
            ProgressionAchievementCriterionType.totalRuleValueAtLeast,
        title: 'Ten-Million Trek',
        description: 'Accumulate 10,000,000 total steps.',
        targetValue: 10000000,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'steps_streak_100',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Centurion Chain',
        description: 'Hit the daily steps rule for 100 periods in a row.',
        targetValue: 100,
        ruleId: 'daily_steps',
      ),
      ProgressionAchievementDefinition(
        id: 'nutrition_streak_100',
        type: ProgressionAchievementType.streak,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.bestStreakAtLeast,
        title: 'Kitchen Discipline',
        description:
            'Earn at least one nutrition reward for 100 periods in a row.',
        targetValue: 100,
        domain: ProgressionDomain.nutrition,
      ),
      ProgressionAchievementDefinition(
        id: 'weekly_activity_52',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType.rewardCountAtLeast,
        title: 'Yearlong Engine',
        description: 'Complete the weekly activity rule 52 times.',
        targetValue: 52,
        ruleId: 'weekly_activity',
      ),
      ProgressionAchievementDefinition(
        id: 'sleep_month_240h',
        type: ProgressionAchievementType.mastery,
        difficulty: ProgressionAchievementDifficulty.extraHard,
        criterionType: ProgressionAchievementCriterionType
            .bestRollingWindowRuleValueAtLeast,
        title: 'Perfect Recovery',
        description: 'Accumulate 240 hours of sleep across any 30-day window.',
        targetValue: 14400,
        ruleId: 'daily_sleep',
        windowSizeDays: 30,
      ),
    ];
  }
}
