// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAktj7dOFqFp5fzLs5trXh1p1UXil9JtU',
    appId: '1:798278342104:web:2af22d64b82bef5261cead',
    messagingSenderId: '798278342104',
    projectId: 'forgetracker-493415',
    authDomain: 'forgetracker-493415.firebaseapp.com',
    databaseURL: 'https://forgetracker-493415-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'forgetracker-493415.firebasestorage.app',
    measurementId: 'G-HB18MWWRM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7iq6TdhiH7VBvH2F4KoEFVsNa-Z5vr4',
    appId: '1:798278342104:android:a44ecd497db4f28161cead',
    messagingSenderId: '798278342104',
    projectId: 'forgetracker-493415',
    databaseURL: 'https://forgetracker-493415-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'forgetracker-493415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsxQPIDufiuvqFttsmcF6jnspzIPhBZow',
    appId: '1:798278342104:ios:e2e8c6b58c33d0d261cead',
    messagingSenderId: '798278342104',
    projectId: 'forgetracker-493415',
    databaseURL: 'https://forgetracker-493415-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'forgetracker-493415.firebasestorage.app',
    androidClientId: '798278342104-jvtmm2jqhnrgpg4f4c12jm2osdi3vurc.apps.googleusercontent.com',
    iosClientId: '798278342104-53il3va0f0j27r0duhi1s2qb9rv4fdkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.forgetracker',
  );
}
